-- SHARPIE roster seed. Safe to re-run: upserts only public.sharpie_students.
insert into public.sharpie_students (login, display_name, class_code, group_name)
values
  ('anazancaner', 'Ana Beatriz Lerio Zancaner', '9A', 'Amarelo'),
  ('anamascarenhas', 'Ana Luiza Netto Mascarenhas', '9A', 'Branco'),
  ('anazimmermann', 'Ana Teresa Ferreira da Rosa Zimmermann', '9A', 'Branco'),
  ('antoniobiagi', 'Antonio Augusto Sandoval Biagi', '9A', 'Amarelo'),
  ('aymanayache', 'Ayman Ayache', '9A', 'Amarelo'),
  ('beatrizsantos', 'Beatriz Uliana dos Santos', '9A', 'Amarelo'),
  ('bernardomagalhaes', 'Bernardo Marcondes Magalhães', '9A', 'Amarelo'),
  ('catarinamoreira', 'Catarina Sá Moreira', '9A', 'Branco'),
  ('felipejardim', 'Felipe Duarte Jardim', '9A', 'Branco'),
  ('felipeceneviva', 'Felipe Serra Ceneviva', '9A', 'Branco'),
  ('gabrielszego', 'Gabriel Kenzo Sakai Szego', '9A', 'Branco'),
  ('giuliapinto', 'Giulia Borghi Pinto', '9A', 'Branco'),
  ('henriquemarsaioli', 'Henrique Botelho Marsaioli', '9A', 'Amarelo'),
  ('isabelalogiodice', 'Isabela Manzini Logiodice', '9A', 'Amarelo'),
  ('joaodedivitis', 'João Pedro Dedivitis', '9A', 'Amarelo'),
  ('juliacastro', 'Julia O''Reilly de Araujo Castro', '9A', 'Amarelo'),
  ('julietaribeiro', 'Julieta Bresser Pereira de Oliveira Ribeiro', '9A', 'Branco'),
  ('lauramendonca', 'Laura Bellinato Mendonça', '9A', 'Amarelo'),
  ('lorenacoffone', 'Lorena Hirsch Coffone', '9A', 'Amarelo'),
  ('lorenzoviccari', 'Lorenzo Giacomazzi Viccari', '9A', 'Amarelo'),
  ('manuelamoraes', 'Manuela Pekelman Levy Leite de Moraes', '9A', 'Amarelo'),
  ('mariagomes', 'Maria Luiza Neiva Ferreira Gomes', '9A', 'Amarelo'),
  ('marianavarella', 'Mariana Orlandi Varella', '9A', 'Amarelo'),
  ('pedromurata', 'Pedro Barros Murata', '9A', 'Branco'),
  ('rafaelandrade', 'Rafael Martin Soares de Andrade', '9A', 'Amarelo'),
  ('raphaelsalerno', 'Raphael Bogus Salerno', '9A', 'Branco'),
  ('anawerneck', 'Ana Beatriz da Silva Werneck', '9B', 'Amarelo'),
  ('catherinekassis', 'Catherine Ajaj Kassis', '9B', 'Amarelo'),
  ('fernandasantos', 'Fernanda Uliana dos Santos', '9B', 'Branco'),
  ('guilhermeminders', 'Guilherme Castilho de Nicola Minders', '9B', 'Branco'),
  ('henriquemovizzo', 'Henrique Arana Movizzo', '9B', 'Branco'),
  ('henriquesilva', 'Henrique Junqueira de Freitas e Silva', '9B', null),
  ('joaojereissati', 'Joao Pedro Gasparian Jereissati', '9B', 'Branco'),
  ('joaquimcardoso', 'Joaquim Lehmkuhl Cardoso', '9B', 'Amarelo'),
  ('joaomandur', 'João Pinheiro Esberard Mandur', '9B', 'Amarelo'),
  ('lauramartins', 'Laura Merêncio Martins', '9B', 'Amarelo'),
  ('lucabertocco', 'Luca Just Bertocco', '9B', 'Amarelo'),
  ('manuelaamendoeira', 'Manuela Amendoeira', '9B', 'Branco'),
  ('manuelatognotti', 'Manuela Tognotti', '9B', 'Branco'),
  ('marcelovalente', 'Marcelo Mota Valente', '9B', 'Amarelo'),
  ('mariamachado', 'Maria Luiza Brandão Machado', '9B', 'Amarelo'),
  ('mariacarneiro', 'Maria de Souza Carneiro', '9B', 'Branco'),
  ('matheuscarnevalli', 'Matheus Gazal Carnevalli', '9B', 'Branco'),
  ('nicolaslopes', 'Nicolas Lopes', '9B', 'Amarelo'),
  ('omarabissamra', 'Omar Fletcher Abissamra', '9B', 'Amarelo'),
  ('rafaelmestieri', 'Rafael Braga Mestieri', '9B', 'Branco'),
  ('rafaelagiacchetta', 'Rafaela Azzi Giacchetta', '9B', 'Amarelo'),
  ('ricardonogueira', 'Ricardo Mckenzie Nogueira', '9B', 'Amarelo'),
  ('robertalepiani', 'Roberta Barbieri Lepiani', '9B', 'Branco'),
  ('saralima', 'Sara Ribeiro dos Santos Lima', '9B', 'Branco'),
  ('stelanahas', 'Stela Amaral Nahas', '9B', 'Branco'),
  ('theopires', 'Theo Baracat Guedes Pires', '9B', 'Amarelo'),
  ('tomasbranco', 'Tomás Vaccaro Castelo Branco', '9B', 'Branco'),
  ('vitorgarofallo', 'Vitor Eduardo Bedotti Garofallo', '9B', 'Amarelo'),
  ('alinesako', 'Aline Jacobini Sako', '9C', 'Branco'),
  ('bernardozelazo', 'Bernardo David Zelazo', '9C', 'Branco'),
  ('brunoalves', 'Bruno Valdemarin Alves', '9C', 'Amarelo'),
  ('eduardoviegas', 'Eduardo Martins Vieira Viegas', '9C', 'Branco'),
  ('eleonoratchalian', 'Eleonora Palenga Tchalian', '9C', 'Amarelo'),
  ('fabiomattos', 'Fabio Dias da Silva Nagliati Mattos', '9C', 'Branco'),
  ('franciscoarantes', 'Francisco Teodoro Arantes', '9C', 'Amarelo'),
  ('gabrielametzger', 'Gabriela Alonso Metzger', '9C', 'Amarelo'),
  ('gabrielamarques', 'Gabriela Chevrier Marques', '9C', 'Branco'),
  ('gabrielasantos', 'Gabriela Uliana dos Santos', '9C', 'Branco'),
  ('giancarloblumetti', 'Giancarlo Pinto Blumetti', '9C', 'Branco'),
  ('joaoschlochauer', 'João Kohl Schlochauer', '9C', 'Branco'),
  ('juliajereissati', 'Julia Gasparian Jereissati', '9C', 'Branco'),
  ('julialeite', 'Julia Salles Leite', '9C', null),
  ('leonardopinto', 'Leonardo Peres Goettert Pinto', '9C', 'Branco'),
  ('lorenzoprado', 'Lorenzo Manini Prado', '9C', 'Amarelo'),
  ('luistoscano', 'Luis Felipe Borges Berardo Toscano', '9C', 'Amarelo'),
  ('marcelladomingues', 'Marcella Ferraro Domingues', '9C', 'Branco'),
  ('matheusmaiorano', 'Matheus Panzan Maiorano', '9C', 'Amarelo'),
  ('paolalarocca', 'Paola Prada Larocca', '9C', 'Branco'),
  ('rodrigomaggioli', 'Rodrigo Maggioli', '9C', 'Branco'),
  ('samiramani', 'Samira Mani', '9C', 'Amarelo'),
  ('sophiaandrade', 'Sophia Valente Andrade', '9C', 'Branco'),
  ('vickyxie', 'Vicky Zhuo Qi Xie', '9C', 'Amarelo'),
  ('carolinaramos', 'Carolina de Oliveira Ramos', '9D', 'Branco'),
  ('constanzacampofiorito', 'Constanza Ferreira Campofiorito', '9D', 'Branco'),
  ('elenaantiquera', 'Elena Massara Antiquera', '9D', 'Amarelo'),
  ('felipefranklin', 'Felipe de Almeida Franklin', '9D', 'Amarelo'),
  ('fredericomaligo', 'Frederico Vianna Maligo', '9D', 'Branco'),
  ('gabrielacuram', 'Gabriela Mello Curam', '9D', 'Branco'),
  ('gianlucabarone', 'Gianluca Sciallis Barone', '9D', 'Branco'),
  ('guilhermelitwin', 'Guilherme Moraes Stolf Litwin', '9D', 'Amarelo'),
  ('gustavocheli', 'Gustavo Velasco Oliveira Cheli', '9D', 'Amarelo'),
  ('henriquesantos', 'Henrique Gomes dos Santos', '9D', 'Branco'),
  ('isabellajafet', 'Isabella Saad Jafet', '9D', 'Branco'),
  ('joaquimrosa', 'Joaquim Soto Garcia Rosa', '9D', 'Amarelo'),
  ('joaoronzella', 'João Taddei Ronzella', '9D', 'Branco'),
  ('larasarhan', 'Lara Boscardin Sarhan', '9D', 'Amarelo'),
  ('luizapato', 'Luiza Bresser Pato', '9D', 'Branco'),
  ('manuelaloureiro', 'Manuela Licio Trigo de Loureiro', '9D', 'Amarelo'),
  ('mariaveloso', 'Maria Beatriz Pinto Veloso', '9D', 'Amarelo'),
  ('miguelcoxo', 'Miguel Figueiredo Baldaia Coxo', '9D', 'Branco'),
  ('oliviamanssur', 'Olivia Zanchet Manssur', '9D', 'Branco'),
  ('patriciapierotti', 'Patricia Vianna Pierotti', '9D', 'Branco'),
  ('patrickcollard', 'Patrick Martino Collard', '9D', 'Branco'),
  ('rafaelcampos', 'Rafael Renda Campos', '9D', 'Amarelo'),
  ('rodrigoszlejf', 'Rodrigo Szlejf', '9D', 'Amarelo'),
  ('stellaazzi', 'Stella Paranhos Azzi', '9D', 'Amarelo')
on conflict (login) do update set
  display_name = excluded.display_name,
  class_code = excluded.class_code,
  group_name = excluded.group_name;
